export const BILLING_TYPES = {
	PAYG: "payg",
	ENTERPRISE: "enterprise",
};

export const IS_LOCALHOST = window?.location?.hostname === "localhost";

// Comprehensive list of country phone codes for all countries worldwide
export const COUNTRY_CODES = [
	// Africa
	{ code: "+213", country: "Algeria", flag: "🇩🇿" },
	{ code: "+244", country: "Angola", flag: "🇦🇴" },
	{ code: "+229", country: "Benin", flag: "🇧🇯" },
	{ code: "+267", country: "Botswana", flag: "🇧🇼" },
	{ code: "+226", country: "Burkina Faso", flag: "🇧🇫" },
	{ code: "+257", country: "Burundi", flag: "🇧🇮" },
	{ code: "+237", country: "Cameroon", flag: "🇨🇲" },
	{ code: "+238", country: "Cape Verde", flag: "🇨🇻" },
	{ code: "+236", country: "Central African Republic", flag: "🇨🇫" },
	{ code: "+235", country: "Chad", flag: "🇹🇩" },
	{ code: "+269", country: "Comoros", flag: "🇰🇲" },
	{ code: "+243", country: "Congo (DRC)", flag: "🇨🇩" },
	{ code: "+242", country: "Congo (Republic)", flag: "🇨🇬" },
	{ code: "+225", country: "Côte d'Ivoire", flag: "🇨🇮" },
	{ code: "+253", country: "Djibouti", flag: "🇩🇯" },
	{ code: "+20", country: "Egypt", flag: "🇪🇬" },
	{ code: "+240", country: "Equatorial Guinea", flag: "🇬🇶" },
	{ code: "+291", country: "Eritrea", flag: "🇪🇷" },
	{ code: "+268", country: "Eswatini", flag: "🇸🇿" },
	{ code: "+251", country: "Ethiopia", flag: "🇪🇹" },
	{ code: "+241", country: "Gabon", flag: "🇬🇦" },
	{ code: "+220", country: "Gambia", flag: "🇬🇲" },
	{ code: "+233", country: "Ghana", flag: "🇬🇭" },
	{ code: "+224", country: "Guinea", flag: "🇬🇳" },
	{ code: "+245", country: "Guinea-Bissau", flag: "🇬🇼" },
	{ code: "+254", country: "Kenya", flag: "🇰🇪" },
	{ code: "+266", country: "Lesotho", flag: "🇱🇸" },
	{ code: "+231", country: "Liberia", flag: "🇱🇷" },
	{ code: "+218", country: "Libya", flag: "🇱🇾" },
	{ code: "+261", country: "Madagascar", flag: "🇲🇬" },
	{ code: "+265", country: "Malawi", flag: "🇲🇼" },
	{ code: "+223", country: "Mali", flag: "🇲🇱" },
	{ code: "+222", country: "Mauritania", flag: "🇲🇷" },
	{ code: "+230", country: "Mauritius", flag: "🇲🇺" },
	{ code: "+262", country: "Mayotte", flag: "🇾🇹" },
	{ code: "+212", country: "Morocco", flag: "🇲🇦" },
	{ code: "+258", country: "Mozambique", flag: "🇲🇿" },
	{ code: "+264", country: "Namibia", flag: "🇳🇦" },
	{ code: "+227", country: "Niger", flag: "🇳🇪" },
	{ code: "+234", country: "Nigeria", flag: "🇳🇬" },
	{ code: "+262", country: "Réunion", flag: "🇷🇪" },
	{ code: "+250", country: "Rwanda", flag: "🇷🇼" },
	{ code: "+290", country: "Saint Helena", flag: "🇸🇭" },
	{ code: "+239", country: "São Tomé and Príncipe", flag: "🇸🇹" },
	{ code: "+221", country: "Senegal", flag: "🇸🇳" },
	{ code: "+248", country: "Seychelles", flag: "🇸🇨" },
	{ code: "+232", country: "Sierra Leone", flag: "🇸🇱" },
	{ code: "+252", country: "Somalia", flag: "🇸🇴" },
	{ code: "+27", country: "South Africa", flag: "🇿🇦" },
	{ code: "+211", country: "South Sudan", flag: "🇸🇸" },
	{ code: "+249", country: "Sudan", flag: "🇸🇩" },
	{ code: "+255", country: "Tanzania", flag: "🇹🇿" },
	{ code: "+228", country: "Togo", flag: "🇹🇬" },
	{ code: "+216", country: "Tunisia", flag: "🇹🇳" },
	{ code: "+256", country: "Uganda", flag: "🇺🇬" },
	{ code: "+260", country: "Zambia", flag: "🇿🇲" },
	{ code: "+263", country: "Zimbabwe", flag: "🇿🇼" },

	// Asia
	{ code: "+93", country: "Afghanistan", flag: "🇦🇫" },
	{ code: "+374", country: "Armenia", flag: "🇦🇲" },
	{ code: "+994", country: "Azerbaijan", flag: "🇦🇿" },
	{ code: "+973", country: "Bahrain", flag: "🇧🇭" },
	{ code: "+880", country: "Bangladesh", flag: "🇧🇩" },
	{ code: "+975", country: "Bhutan", flag: "🇧🇹" },
	{ code: "+673", country: "Brunei", flag: "🇧🇳" },
	{ code: "+855", country: "Cambodia", flag: "🇰🇭" },
	{ code: "+86", country: "China", flag: "🇨🇳" },
	{ code: "+357", country: "Cyprus", flag: "🇨🇾" },
	{ code: "+995", country: "Georgia", flag: "🇬🇪" },
	{ code: "+852", country: "Hong Kong", flag: "🇭🇰" },
	{ code: "+91", country: "India", flag: "🇮🇳" },
	{ code: "+62", country: "Indonesia", flag: "🇮🇩" },
	{ code: "+98", country: "Iran", flag: "🇮🇷" },
	{ code: "+964", country: "Iraq", flag: "🇮🇶" },
	{ code: "+972", country: "Israel", flag: "🇮🇱" },
	{ code: "+81", country: "Japan", flag: "🇯🇵" },
	{ code: "+962", country: "Jordan", flag: "🇯🇴" },
	{ code: "+7", country: "Kazakhstan", flag: "🇰🇿" },
	{ code: "+965", country: "Kuwait", flag: "🇰🇼" },
	{ code: "+996", country: "Kyrgyzstan", flag: "🇰🇬" },
	{ code: "+856", country: "Laos", flag: "🇱🇦" },
	{ code: "+961", country: "Lebanon", flag: "🇱🇧" },
	{ code: "+853", country: "Macau", flag: "🇲🇴" },
	{ code: "+60", country: "Malaysia", flag: "🇲🇾" },
	{ code: "+960", country: "Maldives", flag: "🇲🇻" },
	{ code: "+976", country: "Mongolia", flag: "🇲🇳" },
	{ code: "+95", country: "Myanmar", flag: "🇲🇲" },
	{ code: "+977", country: "Nepal", flag: "🇳🇵" },
	{ code: "+850", country: "North Korea", flag: "🇰🇵" },
	{ code: "+968", country: "Oman", flag: "🇴🇲" },
	{ code: "+92", country: "Pakistan", flag: "🇵🇰" },
	{ code: "+970", country: "Palestine", flag: "🇵🇸" },
	{ code: "+63", country: "Philippines", flag: "🇵🇭" },
	{ code: "+974", country: "Qatar", flag: "🇶🇦" },
	{ code: "+966", country: "Saudi Arabia", flag: "🇸🇦" },
	{ code: "+65", country: "Singapore", flag: "🇸🇬" },
	{ code: "+82", country: "South Korea", flag: "🇰🇷" },
	{ code: "+94", country: "Sri Lanka", flag: "🇱🇰" },
	{ code: "+963", country: "Syria", flag: "🇸🇾" },
	{ code: "+886", country: "Taiwan", flag: "🇹🇼" },
	{ code: "+992", country: "Tajikistan", flag: "🇹🇯" },
	{ code: "+66", country: "Thailand", flag: "🇹🇭" },
	{ code: "+670", country: "Timor-Leste", flag: "🇹🇱" },
	{ code: "+90", country: "Turkey", flag: "🇹🇷" },
	{ code: "+993", country: "Turkmenistan", flag: "🇹🇲" },
	{ code: "+971", country: "United Arab Emirates", flag: "🇦🇪" },
	{ code: "+998", country: "Uzbekistan", flag: "🇺🇿" },
	{ code: "+84", country: "Vietnam", flag: "🇻🇳" },
	{ code: "+967", country: "Yemen", flag: "🇾🇪" },

	// Europe
	{ code: "+355", country: "Albania", flag: "🇦🇱" },
	{ code: "+376", country: "Andorra", flag: "🇦🇩" },
	{ code: "+43", country: "Austria", flag: "🇦🇹" },
	{ code: "+375", country: "Belarus", flag: "🇧🇾" },
	{ code: "+32", country: "Belgium", flag: "🇧🇪" },
	{ code: "+387", country: "Bosnia and Herzegovina", flag: "🇧🇦" },
	{ code: "+359", country: "Bulgaria", flag: "🇧🇬" },
	{ code: "+385", country: "Croatia", flag: "🇭🇷" },
	{ code: "+420", country: "Czech Republic", flag: "🇨🇿" },
	{ code: "+45", country: "Denmark", flag: "🇩🇰" },
	{ code: "+372", country: "Estonia", flag: "🇪🇪" },
	{ code: "+358", country: "Finland", flag: "🇫🇮" },
	{ code: "+33", country: "France", flag: "🇫🇷" },
	{ code: "+49", country: "Germany", flag: "🇩🇪" },
	{ code: "+350", country: "Gibraltar", flag: "🇬🇮" },
	{ code: "+30", country: "Greece", flag: "🇬🇷" },
	{ code: "+36", country: "Hungary", flag: "🇭🇺" },
	{ code: "+354", country: "Iceland", flag: "🇮🇸" },
	{ code: "+353", country: "Ireland", flag: "🇮🇪" },
	{ code: "+39", country: "Italy", flag: "🇮🇹" },
	{ code: "+383", country: "Kosovo", flag: "🇽🇰" },
	{ code: "+371", country: "Latvia", flag: "🇱🇻" },
	{ code: "+423", country: "Liechtenstein", flag: "🇱🇮" },
	{ code: "+370", country: "Lithuania", flag: "🇱🇹" },
	{ code: "+352", country: "Luxembourg", flag: "🇱🇺" },
	{ code: "+389", country: "Macedonia", flag: "🇲🇰" },
	{ code: "+356", country: "Malta", flag: "🇲🇹" },
	{ code: "+373", country: "Moldova", flag: "🇲🇩" },
	{ code: "+377", country: "Monaco", flag: "🇲🇨" },
	{ code: "+382", country: "Montenegro", flag: "🇲🇪" },
	{ code: "+31", country: "Netherlands", flag: "🇳🇱" },
	{ code: "+47", country: "Norway", flag: "🇳🇴" },
	{ code: "+48", country: "Poland", flag: "🇵🇱" },
	{ code: "+351", country: "Portugal", flag: "🇵🇹" },
	{ code: "+40", country: "Romania", flag: "🇷🇴" },
	{ code: "+7", country: "Russia", flag: "🇷🇺" },
	{ code: "+378", country: "San Marino", flag: "🇸🇲" },
	{ code: "+381", country: "Serbia", flag: "🇷🇸" },
	{ code: "+421", country: "Slovakia", flag: "🇸🇰" },
	{ code: "+386", country: "Slovenia", flag: "🇸🇮" },
	{ code: "+34", country: "Spain", flag: "🇪🇸" },
	{ code: "+46", country: "Sweden", flag: "🇸🇪" },
	{ code: "+41", country: "Switzerland", flag: "🇨🇭" },
	{ code: "+380", country: "Ukraine", flag: "🇺🇦" },
	{ code: "+44", country: "United Kingdom", flag: "🇬🇧" },
	{ code: "+379", country: "Vatican City", flag: "🇻🇦" },

	// North America
	{ code: "+1", country: "Canada", flag: "🇨🇦" },
	{ code: "+52", country: "Mexico", flag: "🇲🇽" },
	{ code: "+1", country: "United States", flag: "🇺🇸" },

	// Central America & Caribbean
	{ code: "+1-264", country: "Anguilla", flag: "🇦🇮" },
	{ code: "+1-268", country: "Antigua and Barbuda", flag: "🇦🇬" },
	{ code: "+297", country: "Aruba", flag: "🇦🇼" },
	{ code: "+1-242", country: "Bahamas", flag: "🇧🇸" },
	{ code: "+1-246", country: "Barbados", flag: "🇧🇧" },
	{ code: "+501", country: "Belize", flag: "🇧🇿" },
	{ code: "+1-441", country: "Bermuda", flag: "🇧🇲" },
	{ code: "+1-284", country: "British Virgin Islands", flag: "🇻🇬" },
	{ code: "+1-345", country: "Cayman Islands", flag: "🇰🇾" },
	{ code: "+506", country: "Costa Rica", flag: "🇨🇷" },
	{ code: "+53", country: "Cuba", flag: "🇨🇺" },
	{ code: "+599", country: "Curaçao", flag: "🇨🇼" },
	{ code: "+1-767", country: "Dominica", flag: "🇩🇲" },
	{ code: "+1-809", country: "Dominican Republic", flag: "🇩🇴" },
	{ code: "+503", country: "El Salvador", flag: "🇸🇻" },
	{ code: "+1-473", country: "Grenada", flag: "🇬🇩" },
	{ code: "+502", country: "Guatemala", flag: "🇬🇹" },
	{ code: "+509", country: "Haiti", flag: "🇭🇹" },
	{ code: "+504", country: "Honduras", flag: "🇭🇳" },
	{ code: "+1-876", country: "Jamaica", flag: "🇯🇲" },
	{ code: "+1-664", country: "Montserrat", flag: "🇲🇸" },
	{ code: "+505", country: "Nicaragua", flag: "🇳🇮" },
	{ code: "+507", country: "Panama", flag: "🇵🇦" },
	{ code: "+1-787", country: "Puerto Rico", flag: "🇵🇷" },
	{ code: "+1-869", country: "Saint Kitts and Nevis", flag: "🇰🇳" },
	{ code: "+1-758", country: "Saint Lucia", flag: "🇱🇨" },
	{ code: "+1-784", country: "Saint Vincent", flag: "🇻🇨" },
	{ code: "+1-868", country: "Trinidad and Tobago", flag: "🇹🇹" },
	{ code: "+1-649", country: "Turks and Caicos", flag: "🇹🇨" },

	// South America
	{ code: "+54", country: "Argentina", flag: "🇦🇷" },
	{ code: "+591", country: "Bolivia", flag: "🇧🇴" },
	{ code: "+55", country: "Brazil", flag: "🇧🇷" },
	{ code: "+56", country: "Chile", flag: "🇨🇱" },
	{ code: "+57", country: "Colombia", flag: "🇨🇴" },
	{ code: "+593", country: "Ecuador", flag: "🇪🇨" },
	{ code: "+594", country: "French Guiana", flag: "🇬🇫" },
	{ code: "+592", country: "Guyana", flag: "🇬🇾" },
	{ code: "+595", country: "Paraguay", flag: "🇵🇾" },
	{ code: "+51", country: "Peru", flag: "🇵🇪" },
	{ code: "+597", country: "Suriname", flag: "🇸🇷" },
	{ code: "+598", country: "Uruguay", flag: "🇺🇾" },
	{ code: "+58", country: "Venezuela", flag: "🇻🇪" },

	// Oceania
	{ code: "+61", country: "Australia", flag: "🇦🇺" },
	{ code: "+679", country: "Fiji", flag: "🇫🇯" },
	{ code: "+686", country: "Kiribati", flag: "🇰🇮" },
	{ code: "+692", country: "Marshall Islands", flag: "🇲🇭" },
	{ code: "+691", country: "Micronesia", flag: "🇫🇲" },
	{ code: "+674", country: "Nauru", flag: "🇳🇷" },
	{ code: "+687", country: "New Caledonia", flag: "🇳🇨" },
	{ code: "+64", country: "New Zealand", flag: "🇳🇿" },
	{ code: "+680", country: "Palau", flag: "🇵🇼" },
	{ code: "+675", country: "Papua New Guinea", flag: "🇵🇬" },
	{ code: "+685", country: "Samoa", flag: "🇼🇸" },
	{ code: "+677", country: "Solomon Islands", flag: "🇸🇧" },
	{ code: "+676", country: "Tonga", flag: "🇹🇴" },
	{ code: "+688", country: "Tuvalu", flag: "🇹🇻" },
	{ code: "+678", country: "Vanuatu", flag: "🇻🇺" },
];

export const COUNTRIES = [
	{ code: "AF", name: "Afghanistan" },
	{ code: "AL", name: "Albania" },
	{ code: "DZ", name: "Algeria" },
	{ code: "AD", name: "Andorra" },
	{ code: "AO", name: "Angola" },
	{ code: "AG", name: "Antigua and Barbuda" },
	{ code: "AR", name: "Argentina" },
	{ code: "AM", name: "Armenia" },
	{ code: "AU", name: "Australia" },
	{ code: "AT", name: "Austria" },
	{ code: "AZ", name: "Azerbaijan" },
	{ code: "BS", name: "Bahamas" },
	{ code: "BH", name: "Bahrain" },
	{ code: "BD", name: "Bangladesh" },
	{ code: "BB", name: "Barbados" },
	{ code: "BY", name: "Belarus" },
	{ code: "BE", name: "Belgium" },
	{ code: "BZ", name: "Belize" },
	{ code: "BJ", name: "Benin" },
	{ code: "BT", name: "Bhutan" },
	{ code: "BO", name: "Bolivia" },
	{ code: "BA", name: "Bosnia and Herzegovina" },
	{ code: "BW", name: "Botswana" },
	{ code: "BR", name: "Brazil" },
	{ code: "BN", name: "Brunei" },
	{ code: "BG", name: "Bulgaria" },
	{ code: "BF", name: "Burkina Faso" },
	{ code: "BI", name: "Burundi" },
	{ code: "CV", name: "Cabo Verde" },
	{ code: "KH", name: "Cambodia" },
	{ code: "CM", name: "Cameroon" },
	{ code: "CA", name: "Canada" },
	{ code: "CF", name: "Central African Republic" },
	{ code: "TD", name: "Chad" },
	{ code: "CL", name: "Chile" },
	{ code: "CN", name: "China" },
	{ code: "CO", name: "Colombia" },
	{ code: "KM", name: "Comoros" },
	{ code: "CG", name: "Congo" },
	{ code: "CD", name: "Congo (Democratic Republic)" },
	{ code: "CR", name: "Costa Rica" },
	{ code: "CI", name: "Côte d'Ivoire" },
	{ code: "HR", name: "Croatia" },
	{ code: "CU", name: "Cuba" },
	{ code: "CY", name: "Cyprus" },
	{ code: "CZ", name: "Czech Republic" },
	{ code: "DK", name: "Denmark" },
	{ code: "DJ", name: "Djibouti" },
	{ code: "DM", name: "Dominica" },
	{ code: "DO", name: "Dominican Republic" },
	{ code: "EC", name: "Ecuador" },
	{ code: "EG", name: "Egypt" },
	{ code: "SV", name: "El Salvador" },
	{ code: "GQ", name: "Equatorial Guinea" },
	{ code: "ER", name: "Eritrea" },
	{ code: "EE", name: "Estonia" },
	{ code: "SZ", name: "Eswatini" },
	{ code: "ET", name: "Ethiopia" },
	{ code: "FJ", name: "Fiji" },
	{ code: "FI", name: "Finland" },
	{ code: "FR", name: "France" },
	{ code: "GA", name: "Gabon" },
	{ code: "GM", name: "Gambia" },
	{ code: "GE", name: "Georgia" },
	{ code: "DE", name: "Germany" },
	{ code: "GH", name: "Ghana" },
	{ code: "GR", name: "Greece" },
	{ code: "GD", name: "Grenada" },
	{ code: "GT", name: "Guatemala" },
	{ code: "GN", name: "Guinea" },
	{ code: "GW", name: "Guinea-Bissau" },
	{ code: "GY", name: "Guyana" },
	{ code: "HT", name: "Haiti" },
	{ code: "HN", name: "Honduras" },
	{ code: "HU", name: "Hungary" },
	{ code: "IS", name: "Iceland" },
	{ code: "IN", name: "India" },
	{ code: "ID", name: "Indonesia" },
	{ code: "IR", name: "Iran" },
	{ code: "IQ", name: "Iraq" },
	{ code: "IE", name: "Ireland" },
	{ code: "IL", name: "Israel" },
	{ code: "IT", name: "Italy" },
	{ code: "JM", name: "Jamaica" },
	{ code: "JP", name: "Japan" },
	{ code: "JO", name: "Jordan" },
	{ code: "KZ", name: "Kazakhstan" },
	{ code: "KE", name: "Kenya" },
	{ code: "KI", name: "Kiribati" },
	{ code: "KP", name: "Korea (North)" },
	{ code: "KR", name: "Korea (South)" },
	{ code: "KW", name: "Kuwait" },
	{ code: "KG", name: "Kyrgyzstan" },
	{ code: "LA", name: "Laos" },
	{ code: "LV", name: "Latvia" },
	{ code: "LB", name: "Lebanon" },
	{ code: "LS", name: "Lesotho" },
	{ code: "LR", name: "Liberia" },
	{ code: "LY", name: "Libya" },
	{ code: "LI", name: "Liechtenstein" },
	{ code: "LT", name: "Lithuania" },
	{ code: "LU", name: "Luxembourg" },
	{ code: "MG", name: "Madagascar" },
	{ code: "MW", name: "Malawi" },
	{ code: "MY", name: "Malaysia" },
	{ code: "MV", name: "Maldives" },
	{ code: "ML", name: "Mali" },
	{ code: "MT", name: "Malta" },
	{ code: "MH", name: "Marshall Islands" },
	{ code: "MR", name: "Mauritania" },
	{ code: "MU", name: "Mauritius" },
	{ code: "MX", name: "Mexico" },
	{ code: "FM", name: "Micronesia" },
	{ code: "MD", name: "Moldova" },
	{ code: "MC", name: "Monaco" },
	{ code: "MN", name: "Mongolia" },
	{ code: "ME", name: "Montenegro" },
	{ code: "MA", name: "Morocco" },
	{ code: "MZ", name: "Mozambique" },
	{ code: "MM", name: "Myanmar" },
	{ code: "NA", name: "Namibia" },
	{ code: "NR", name: "Nauru" },
	{ code: "NP", name: "Nepal" },
	{ code: "NL", name: "Netherlands" },
	{ code: "NZ", name: "New Zealand" },
	{ code: "NI", name: "Nicaragua" },
	{ code: "NE", name: "Niger" },
	{ code: "NG", name: "Nigeria" },
	{ code: "MK", name: "North Macedonia" },
	{ code: "NO", name: "Norway" },
	{ code: "OM", name: "Oman" },
	{ code: "PK", name: "Pakistan" },
	{ code: "PW", name: "Palau" },
	{ code: "PS", name: "Palestine" },
	{ code: "PA", name: "Panama" },
	{ code: "PG", name: "Papua New Guinea" },
	{ code: "PY", name: "Paraguay" },
	{ code: "PE", name: "Peru" },
	{ code: "PH", name: "Philippines" },
	{ code: "PL", name: "Poland" },
	{ code: "PT", name: "Portugal" },
	{ code: "QA", name: "Qatar" },
	{ code: "RO", name: "Romania" },
	{ code: "RU", name: "Russia" },
	{ code: "RW", name: "Rwanda" },
	{ code: "KN", name: "Saint Kitts and Nevis" },
	{ code: "LC", name: "Saint Lucia" },
	{ code: "VC", name: "Saint Vincent and the Grenadines" },
	{ code: "WS", name: "Samoa" },
	{ code: "SM", name: "San Marino" },
	{ code: "ST", name: "São Tomé and Príncipe" },
	{ code: "SA", name: "Saudi Arabia" },
	{ code: "SN", name: "Senegal" },
	{ code: "RS", name: "Serbia" },
	{ code: "SC", name: "Seychelles" },
	{ code: "SL", name: "Sierra Leone" },
	{ code: "SG", name: "Singapore" },
	{ code: "SK", name: "Slovakia" },
	{ code: "SI", name: "Slovenia" },
	{ code: "SB", name: "Solomon Islands" },
	{ code: "SO", name: "Somalia" },
	{ code: "ZA", name: "South Africa" },
	{ code: "SS", name: "South Sudan" },
	{ code: "ES", name: "Spain" },
	{ code: "LK", name: "Sri Lanka" },
	{ code: "SD", name: "Sudan" },
	{ code: "SR", name: "Suriname" },
	{ code: "SE", name: "Sweden" },
	{ code: "CH", name: "Switzerland" },
	{ code: "SY", name: "Syria" },
	{ code: "TW", name: "Taiwan" },
	{ code: "TJ", name: "Tajikistan" },
	{ code: "TZ", name: "Tanzania" },
	{ code: "TH", name: "Thailand" },
	{ code: "TL", name: "Timor-Leste" },
	{ code: "TG", name: "Togo" },
	{ code: "TO", name: "Tonga" },
	{ code: "TT", name: "Trinidad and Tobago" },
	{ code: "TN", name: "Tunisia" },
	{ code: "TR", name: "Turkey" },
	{ code: "TM", name: "Turkmenistan" },
	{ code: "TV", name: "Tuvalu" },
	{ code: "UG", name: "Uganda" },
	{ code: "UA", name: "Ukraine" },
	{ code: "AE", name: "United Arab Emirates" },
	{ code: "GB", name: "United Kingdom" },
	{ code: "US", name: "United States" },
	{ code: "UY", name: "Uruguay" },
	{ code: "UZ", name: "Uzbekistan" },
	{ code: "VU", name: "Vanuatu" },
	{ code: "VA", name: "Vatican City" },
	{ code: "VE", name: "Venezuela" },
	{ code: "VN", name: "Vietnam" },
	{ code: "YE", name: "Yemen" },
	{ code: "ZM", name: "Zambia" },
	{ code: "ZW", name: "Zimbabwe" },
];

export const VERIFICATION_TYPES = {
	ZA_SAID_VERIFICATION: {
		value: "za_said_verification",
		label: "South Africa - SA ID",
	},
	NG_BVN_VERIFICATION: {
		value: "ng_bvn_verification",
		label: "Nigeria - BVN",
	},
	NG_NIN_VERIFICATION: {
		value: "ng_nin_verification",
		label: "Nigeria - NIN",
	},
	NG_VIRTUAL_NIN_VERIFICATION: {
		value: "ng_virtual_nin_verification",
		label: "Nigeria - Virtual NIN",
	},
	NG_ADVANCED_PHONE_NUMBER_VERIFICATION: {
		value: "ng_advanced_phone_number_verification",
		label: "Nigeria - Advanced Phone",
	},
	NG_PHONE_NUMBER_LOOKUP: {
		value: "ng_phone_number_lookup",
		label: "Nigeria - Phone Lookup",
	},
	NG_CAC_LOOKUP: {
		value: "ng_cac_lookup",
		label: "Nigeria - CAC Lookup",
	},
	NG_PASSPORT_VERIFICATION: {
		value: "ng_passport_verification",
		label: "Nigeria - Passport Verification",
	},
	GH_PASSPORT_LOOKUP: {
		value: "gh_passport_lookup",
		label: "Ghana - Passport",
	},
	GH_VOTER_CARD_LOOKUP: {
		value: "gh_voter_card_lookup",
		label: "Ghana - Voter Card",
	},
	GH_SSNIT_LOOKUP: {
		value: "gh_ssnit_lookup",
		label: "Ghana - SSNIT",
	},
	GH_DRIVERS_LICENSE_LOOKUP: {
		value: "gh_drivers_license_lookup",
		label: "Ghana - Drivers License",
	},
	KE_PASSPORT_LOOKUP: {
		value: "ke_passport_lookup",
		label: "Kenya - Passport",
	},
	KE_NATIONAL_ID_LOOKUP: {
		value: "ke_national_id_lookup",
		label: "Kenya - National ID",
	},
	KE_PHONE_NUMBER_LOOKUP: {
		value: "ke_phone_number_lookup",
		label: "Kenya - Phone Lookup",
	},
	KE_TAX_PIN_VERIFICATION: {
		value: "ke_tax_pin_verification",
		label: "Kenya - Tax PIN",
	},
};

export const SHUFTI_CHOICES = {
	YES: "1",
	NO: "0",
	ANY: "any",
};

export const SHUFTI_VERIFICATION_TYPES = {
	DOCUMENT_VERIFICATION: "id_document",
	FACIAL_VERIFICATION: "face_match",
	ADDRESS_VERIFICATION: "address_verification",
	AML_SCREENING: "aml_screening",
	BUSINESS_AML_SCREENING: "business_aml_screening",
	CRYPTO_WALLET_SCREENING: "crypto_wallet_screening",
	KYB_VERIFICATION: "kyb_screening",
	RISK_ASSESSMENT: "risk_assessment",
	AGE_VERIFICATION: "age_verification",
};
