/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authLayoutRouteImport } from './routes/(auth)/_layout'
import { Route as authLayoutDashboardIndexRouteImport } from './routes/(auth)/_layout/dashboard/index'
import { Route as authLayoutDashboardTeamIndexRouteImport } from './routes/(auth)/_layout/dashboard/team/index'
import { Route as authLayoutDashboardProfileIndexRouteImport } from './routes/(auth)/_layout/dashboard/profile/index'
import { Route as authLayoutDashboardProductsIndexRouteImport } from './routes/(auth)/_layout/dashboard/products/index'
import { Route as authLayoutDashboardBillingIndexRouteImport } from './routes/(auth)/_layout/dashboard/billing/index'
import { Route as authLayoutDashboardApikeysIndexRouteImport } from './routes/(auth)/_layout/dashboard/apikeys/index'
import { Route as authLayoutDashboardProductsRiskAssessmentIndexRouteImport } from './routes/(auth)/_layout/dashboard/products/risk-assessment/index'
import { Route as authLayoutDashboardProductsKybIndexRouteImport } from './routes/(auth)/_layout/dashboard/products/kyb/index'
import { Route as authLayoutDashboardProductsGovernmentRegistryChecksIndexRouteImport } from './routes/(auth)/_layout/dashboard/products/government-registry-checks/index'
import { Route as authLayoutDashboardProductsFacialScreeningIndexRouteImport } from './routes/(auth)/_layout/dashboard/products/facial-screening/index'
import { Route as authLayoutDashboardProductsDocumentVerificationIndexRouteImport } from './routes/(auth)/_layout/dashboard/products/document-verification/index'
import { Route as authLayoutDashboardProductsCryptoWalletScreeningIndexRouteImport } from './routes/(auth)/_layout/dashboard/products/crypto-wallet-screening/index'
import { Route as authLayoutDashboardProductsBusinessAmlScreeningIndexRouteImport } from './routes/(auth)/_layout/dashboard/products/business-aml-screening/index'
import { Route as authLayoutDashboardProductsAmlScreeningIndexRouteImport } from './routes/(auth)/_layout/dashboard/products/aml-screening/index'
import { Route as authLayoutDashboardProductsAddressVerificationIndexRouteImport } from './routes/(auth)/_layout/dashboard/products/address-verification/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authLayoutRoute = authLayoutRouteImport.update({
  id: '/(auth)/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const authLayoutDashboardIndexRoute =
  authLayoutDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => authLayoutRoute,
  } as any)
const authLayoutDashboardTeamIndexRoute =
  authLayoutDashboardTeamIndexRouteImport.update({
    id: '/dashboard/team/',
    path: '/dashboard/team/',
    getParentRoute: () => authLayoutRoute,
  } as any)
const authLayoutDashboardProfileIndexRoute =
  authLayoutDashboardProfileIndexRouteImport.update({
    id: '/dashboard/profile/',
    path: '/dashboard/profile/',
    getParentRoute: () => authLayoutRoute,
  } as any)
const authLayoutDashboardProductsIndexRoute =
  authLayoutDashboardProductsIndexRouteImport.update({
    id: '/dashboard/products/',
    path: '/dashboard/products/',
    getParentRoute: () => authLayoutRoute,
  } as any)
const authLayoutDashboardBillingIndexRoute =
  authLayoutDashboardBillingIndexRouteImport.update({
    id: '/dashboard/billing/',
    path: '/dashboard/billing/',
    getParentRoute: () => authLayoutRoute,
  } as any)
const authLayoutDashboardApikeysIndexRoute =
  authLayoutDashboardApikeysIndexRouteImport.update({
    id: '/dashboard/apikeys/',
    path: '/dashboard/apikeys/',
    getParentRoute: () => authLayoutRoute,
  } as any)
const authLayoutDashboardProductsRiskAssessmentIndexRoute =
  authLayoutDashboardProductsRiskAssessmentIndexRouteImport.update({
    id: '/dashboard/products/risk-assessment/',
    path: '/dashboard/products/risk-assessment/',
    getParentRoute: () => authLayoutRoute,
  } as any)
const authLayoutDashboardProductsKybIndexRoute =
  authLayoutDashboardProductsKybIndexRouteImport.update({
    id: '/dashboard/products/kyb/',
    path: '/dashboard/products/kyb/',
    getParentRoute: () => authLayoutRoute,
  } as any)
const authLayoutDashboardProductsGovernmentRegistryChecksIndexRoute =
  authLayoutDashboardProductsGovernmentRegistryChecksIndexRouteImport.update({
    id: '/dashboard/products/government-registry-checks/',
    path: '/dashboard/products/government-registry-checks/',
    getParentRoute: () => authLayoutRoute,
  } as any)
const authLayoutDashboardProductsFacialScreeningIndexRoute =
  authLayoutDashboardProductsFacialScreeningIndexRouteImport.update({
    id: '/dashboard/products/facial-screening/',
    path: '/dashboard/products/facial-screening/',
    getParentRoute: () => authLayoutRoute,
  } as any)
const authLayoutDashboardProductsDocumentVerificationIndexRoute =
  authLayoutDashboardProductsDocumentVerificationIndexRouteImport.update({
    id: '/dashboard/products/document-verification/',
    path: '/dashboard/products/document-verification/',
    getParentRoute: () => authLayoutRoute,
  } as any)
const authLayoutDashboardProductsCryptoWalletScreeningIndexRoute =
  authLayoutDashboardProductsCryptoWalletScreeningIndexRouteImport.update({
    id: '/dashboard/products/crypto-wallet-screening/',
    path: '/dashboard/products/crypto-wallet-screening/',
    getParentRoute: () => authLayoutRoute,
  } as any)
const authLayoutDashboardProductsBusinessAmlScreeningIndexRoute =
  authLayoutDashboardProductsBusinessAmlScreeningIndexRouteImport.update({
    id: '/dashboard/products/business-aml-screening/',
    path: '/dashboard/products/business-aml-screening/',
    getParentRoute: () => authLayoutRoute,
  } as any)
const authLayoutDashboardProductsAmlScreeningIndexRoute =
  authLayoutDashboardProductsAmlScreeningIndexRouteImport.update({
    id: '/dashboard/products/aml-screening/',
    path: '/dashboard/products/aml-screening/',
    getParentRoute: () => authLayoutRoute,
  } as any)
const authLayoutDashboardProductsAddressVerificationIndexRoute =
  authLayoutDashboardProductsAddressVerificationIndexRouteImport.update({
    id: '/dashboard/products/address-verification/',
    path: '/dashboard/products/address-verification/',
    getParentRoute: () => authLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard/': typeof authLayoutDashboardIndexRoute
  '/dashboard/apikeys/': typeof authLayoutDashboardApikeysIndexRoute
  '/dashboard/billing/': typeof authLayoutDashboardBillingIndexRoute
  '/dashboard/products/': typeof authLayoutDashboardProductsIndexRoute
  '/dashboard/profile/': typeof authLayoutDashboardProfileIndexRoute
  '/dashboard/team/': typeof authLayoutDashboardTeamIndexRoute
  '/dashboard/products/address-verification/': typeof authLayoutDashboardProductsAddressVerificationIndexRoute
  '/dashboard/products/aml-screening/': typeof authLayoutDashboardProductsAmlScreeningIndexRoute
  '/dashboard/products/business-aml-screening/': typeof authLayoutDashboardProductsBusinessAmlScreeningIndexRoute
  '/dashboard/products/crypto-wallet-screening/': typeof authLayoutDashboardProductsCryptoWalletScreeningIndexRoute
  '/dashboard/products/document-verification/': typeof authLayoutDashboardProductsDocumentVerificationIndexRoute
  '/dashboard/products/facial-screening/': typeof authLayoutDashboardProductsFacialScreeningIndexRoute
  '/dashboard/products/government-registry-checks/': typeof authLayoutDashboardProductsGovernmentRegistryChecksIndexRoute
  '/dashboard/products/kyb/': typeof authLayoutDashboardProductsKybIndexRoute
  '/dashboard/products/risk-assessment/': typeof authLayoutDashboardProductsRiskAssessmentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof authLayoutDashboardIndexRoute
  '/dashboard/apikeys': typeof authLayoutDashboardApikeysIndexRoute
  '/dashboard/billing': typeof authLayoutDashboardBillingIndexRoute
  '/dashboard/products': typeof authLayoutDashboardProductsIndexRoute
  '/dashboard/profile': typeof authLayoutDashboardProfileIndexRoute
  '/dashboard/team': typeof authLayoutDashboardTeamIndexRoute
  '/dashboard/products/address-verification': typeof authLayoutDashboardProductsAddressVerificationIndexRoute
  '/dashboard/products/aml-screening': typeof authLayoutDashboardProductsAmlScreeningIndexRoute
  '/dashboard/products/business-aml-screening': typeof authLayoutDashboardProductsBusinessAmlScreeningIndexRoute
  '/dashboard/products/crypto-wallet-screening': typeof authLayoutDashboardProductsCryptoWalletScreeningIndexRoute
  '/dashboard/products/document-verification': typeof authLayoutDashboardProductsDocumentVerificationIndexRoute
  '/dashboard/products/facial-screening': typeof authLayoutDashboardProductsFacialScreeningIndexRoute
  '/dashboard/products/government-registry-checks': typeof authLayoutDashboardProductsGovernmentRegistryChecksIndexRoute
  '/dashboard/products/kyb': typeof authLayoutDashboardProductsKybIndexRoute
  '/dashboard/products/risk-assessment': typeof authLayoutDashboardProductsRiskAssessmentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)/_layout': typeof authLayoutRouteWithChildren
  '/(auth)/_layout/dashboard/': typeof authLayoutDashboardIndexRoute
  '/(auth)/_layout/dashboard/apikeys/': typeof authLayoutDashboardApikeysIndexRoute
  '/(auth)/_layout/dashboard/billing/': typeof authLayoutDashboardBillingIndexRoute
  '/(auth)/_layout/dashboard/products/': typeof authLayoutDashboardProductsIndexRoute
  '/(auth)/_layout/dashboard/profile/': typeof authLayoutDashboardProfileIndexRoute
  '/(auth)/_layout/dashboard/team/': typeof authLayoutDashboardTeamIndexRoute
  '/(auth)/_layout/dashboard/products/address-verification/': typeof authLayoutDashboardProductsAddressVerificationIndexRoute
  '/(auth)/_layout/dashboard/products/aml-screening/': typeof authLayoutDashboardProductsAmlScreeningIndexRoute
  '/(auth)/_layout/dashboard/products/business-aml-screening/': typeof authLayoutDashboardProductsBusinessAmlScreeningIndexRoute
  '/(auth)/_layout/dashboard/products/crypto-wallet-screening/': typeof authLayoutDashboardProductsCryptoWalletScreeningIndexRoute
  '/(auth)/_layout/dashboard/products/document-verification/': typeof authLayoutDashboardProductsDocumentVerificationIndexRoute
  '/(auth)/_layout/dashboard/products/facial-screening/': typeof authLayoutDashboardProductsFacialScreeningIndexRoute
  '/(auth)/_layout/dashboard/products/government-registry-checks/': typeof authLayoutDashboardProductsGovernmentRegistryChecksIndexRoute
  '/(auth)/_layout/dashboard/products/kyb/': typeof authLayoutDashboardProductsKybIndexRoute
  '/(auth)/_layout/dashboard/products/risk-assessment/': typeof authLayoutDashboardProductsRiskAssessmentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard/'
    | '/dashboard/apikeys/'
    | '/dashboard/billing/'
    | '/dashboard/products/'
    | '/dashboard/profile/'
    | '/dashboard/team/'
    | '/dashboard/products/address-verification/'
    | '/dashboard/products/aml-screening/'
    | '/dashboard/products/business-aml-screening/'
    | '/dashboard/products/crypto-wallet-screening/'
    | '/dashboard/products/document-verification/'
    | '/dashboard/products/facial-screening/'
    | '/dashboard/products/government-registry-checks/'
    | '/dashboard/products/kyb/'
    | '/dashboard/products/risk-assessment/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/dashboard/apikeys'
    | '/dashboard/billing'
    | '/dashboard/products'
    | '/dashboard/profile'
    | '/dashboard/team'
    | '/dashboard/products/address-verification'
    | '/dashboard/products/aml-screening'
    | '/dashboard/products/business-aml-screening'
    | '/dashboard/products/crypto-wallet-screening'
    | '/dashboard/products/document-verification'
    | '/dashboard/products/facial-screening'
    | '/dashboard/products/government-registry-checks'
    | '/dashboard/products/kyb'
    | '/dashboard/products/risk-assessment'
  id:
    | '__root__'
    | '/'
    | '/(auth)/_layout'
    | '/(auth)/_layout/dashboard/'
    | '/(auth)/_layout/dashboard/apikeys/'
    | '/(auth)/_layout/dashboard/billing/'
    | '/(auth)/_layout/dashboard/products/'
    | '/(auth)/_layout/dashboard/profile/'
    | '/(auth)/_layout/dashboard/team/'
    | '/(auth)/_layout/dashboard/products/address-verification/'
    | '/(auth)/_layout/dashboard/products/aml-screening/'
    | '/(auth)/_layout/dashboard/products/business-aml-screening/'
    | '/(auth)/_layout/dashboard/products/crypto-wallet-screening/'
    | '/(auth)/_layout/dashboard/products/document-verification/'
    | '/(auth)/_layout/dashboard/products/facial-screening/'
    | '/(auth)/_layout/dashboard/products/government-registry-checks/'
    | '/(auth)/_layout/dashboard/products/kyb/'
    | '/(auth)/_layout/dashboard/products/risk-assessment/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authLayoutRoute: typeof authLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/_layout': {
      id: '/(auth)/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/_layout/dashboard/': {
      id: '/(auth)/_layout/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof authLayoutDashboardIndexRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(auth)/_layout/dashboard/team/': {
      id: '/(auth)/_layout/dashboard/team/'
      path: '/dashboard/team'
      fullPath: '/dashboard/team/'
      preLoaderRoute: typeof authLayoutDashboardTeamIndexRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(auth)/_layout/dashboard/profile/': {
      id: '/(auth)/_layout/dashboard/profile/'
      path: '/dashboard/profile'
      fullPath: '/dashboard/profile/'
      preLoaderRoute: typeof authLayoutDashboardProfileIndexRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(auth)/_layout/dashboard/products/': {
      id: '/(auth)/_layout/dashboard/products/'
      path: '/dashboard/products'
      fullPath: '/dashboard/products/'
      preLoaderRoute: typeof authLayoutDashboardProductsIndexRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(auth)/_layout/dashboard/billing/': {
      id: '/(auth)/_layout/dashboard/billing/'
      path: '/dashboard/billing'
      fullPath: '/dashboard/billing/'
      preLoaderRoute: typeof authLayoutDashboardBillingIndexRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(auth)/_layout/dashboard/apikeys/': {
      id: '/(auth)/_layout/dashboard/apikeys/'
      path: '/dashboard/apikeys'
      fullPath: '/dashboard/apikeys/'
      preLoaderRoute: typeof authLayoutDashboardApikeysIndexRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(auth)/_layout/dashboard/products/risk-assessment/': {
      id: '/(auth)/_layout/dashboard/products/risk-assessment/'
      path: '/dashboard/products/risk-assessment'
      fullPath: '/dashboard/products/risk-assessment/'
      preLoaderRoute: typeof authLayoutDashboardProductsRiskAssessmentIndexRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(auth)/_layout/dashboard/products/kyb/': {
      id: '/(auth)/_layout/dashboard/products/kyb/'
      path: '/dashboard/products/kyb'
      fullPath: '/dashboard/products/kyb/'
      preLoaderRoute: typeof authLayoutDashboardProductsKybIndexRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(auth)/_layout/dashboard/products/government-registry-checks/': {
      id: '/(auth)/_layout/dashboard/products/government-registry-checks/'
      path: '/dashboard/products/government-registry-checks'
      fullPath: '/dashboard/products/government-registry-checks/'
      preLoaderRoute: typeof authLayoutDashboardProductsGovernmentRegistryChecksIndexRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(auth)/_layout/dashboard/products/facial-screening/': {
      id: '/(auth)/_layout/dashboard/products/facial-screening/'
      path: '/dashboard/products/facial-screening'
      fullPath: '/dashboard/products/facial-screening/'
      preLoaderRoute: typeof authLayoutDashboardProductsFacialScreeningIndexRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(auth)/_layout/dashboard/products/document-verification/': {
      id: '/(auth)/_layout/dashboard/products/document-verification/'
      path: '/dashboard/products/document-verification'
      fullPath: '/dashboard/products/document-verification/'
      preLoaderRoute: typeof authLayoutDashboardProductsDocumentVerificationIndexRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(auth)/_layout/dashboard/products/crypto-wallet-screening/': {
      id: '/(auth)/_layout/dashboard/products/crypto-wallet-screening/'
      path: '/dashboard/products/crypto-wallet-screening'
      fullPath: '/dashboard/products/crypto-wallet-screening/'
      preLoaderRoute: typeof authLayoutDashboardProductsCryptoWalletScreeningIndexRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(auth)/_layout/dashboard/products/business-aml-screening/': {
      id: '/(auth)/_layout/dashboard/products/business-aml-screening/'
      path: '/dashboard/products/business-aml-screening'
      fullPath: '/dashboard/products/business-aml-screening/'
      preLoaderRoute: typeof authLayoutDashboardProductsBusinessAmlScreeningIndexRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(auth)/_layout/dashboard/products/aml-screening/': {
      id: '/(auth)/_layout/dashboard/products/aml-screening/'
      path: '/dashboard/products/aml-screening'
      fullPath: '/dashboard/products/aml-screening/'
      preLoaderRoute: typeof authLayoutDashboardProductsAmlScreeningIndexRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(auth)/_layout/dashboard/products/address-verification/': {
      id: '/(auth)/_layout/dashboard/products/address-verification/'
      path: '/dashboard/products/address-verification'
      fullPath: '/dashboard/products/address-verification/'
      preLoaderRoute: typeof authLayoutDashboardProductsAddressVerificationIndexRouteImport
      parentRoute: typeof authLayoutRoute
    }
  }
}

interface authLayoutRouteChildren {
  authLayoutDashboardIndexRoute: typeof authLayoutDashboardIndexRoute
  authLayoutDashboardApikeysIndexRoute: typeof authLayoutDashboardApikeysIndexRoute
  authLayoutDashboardBillingIndexRoute: typeof authLayoutDashboardBillingIndexRoute
  authLayoutDashboardProductsIndexRoute: typeof authLayoutDashboardProductsIndexRoute
  authLayoutDashboardProfileIndexRoute: typeof authLayoutDashboardProfileIndexRoute
  authLayoutDashboardTeamIndexRoute: typeof authLayoutDashboardTeamIndexRoute
  authLayoutDashboardProductsAddressVerificationIndexRoute: typeof authLayoutDashboardProductsAddressVerificationIndexRoute
  authLayoutDashboardProductsAmlScreeningIndexRoute: typeof authLayoutDashboardProductsAmlScreeningIndexRoute
  authLayoutDashboardProductsBusinessAmlScreeningIndexRoute: typeof authLayoutDashboardProductsBusinessAmlScreeningIndexRoute
  authLayoutDashboardProductsCryptoWalletScreeningIndexRoute: typeof authLayoutDashboardProductsCryptoWalletScreeningIndexRoute
  authLayoutDashboardProductsDocumentVerificationIndexRoute: typeof authLayoutDashboardProductsDocumentVerificationIndexRoute
  authLayoutDashboardProductsFacialScreeningIndexRoute: typeof authLayoutDashboardProductsFacialScreeningIndexRoute
  authLayoutDashboardProductsGovernmentRegistryChecksIndexRoute: typeof authLayoutDashboardProductsGovernmentRegistryChecksIndexRoute
  authLayoutDashboardProductsKybIndexRoute: typeof authLayoutDashboardProductsKybIndexRoute
  authLayoutDashboardProductsRiskAssessmentIndexRoute: typeof authLayoutDashboardProductsRiskAssessmentIndexRoute
}

const authLayoutRouteChildren: authLayoutRouteChildren = {
  authLayoutDashboardIndexRoute: authLayoutDashboardIndexRoute,
  authLayoutDashboardApikeysIndexRoute: authLayoutDashboardApikeysIndexRoute,
  authLayoutDashboardBillingIndexRoute: authLayoutDashboardBillingIndexRoute,
  authLayoutDashboardProductsIndexRoute: authLayoutDashboardProductsIndexRoute,
  authLayoutDashboardProfileIndexRoute: authLayoutDashboardProfileIndexRoute,
  authLayoutDashboardTeamIndexRoute: authLayoutDashboardTeamIndexRoute,
  authLayoutDashboardProductsAddressVerificationIndexRoute:
    authLayoutDashboardProductsAddressVerificationIndexRoute,
  authLayoutDashboardProductsAmlScreeningIndexRoute:
    authLayoutDashboardProductsAmlScreeningIndexRoute,
  authLayoutDashboardProductsBusinessAmlScreeningIndexRoute:
    authLayoutDashboardProductsBusinessAmlScreeningIndexRoute,
  authLayoutDashboardProductsCryptoWalletScreeningIndexRoute:
    authLayoutDashboardProductsCryptoWalletScreeningIndexRoute,
  authLayoutDashboardProductsDocumentVerificationIndexRoute:
    authLayoutDashboardProductsDocumentVerificationIndexRoute,
  authLayoutDashboardProductsFacialScreeningIndexRoute:
    authLayoutDashboardProductsFacialScreeningIndexRoute,
  authLayoutDashboardProductsGovernmentRegistryChecksIndexRoute:
    authLayoutDashboardProductsGovernmentRegistryChecksIndexRoute,
  authLayoutDashboardProductsKybIndexRoute:
    authLayoutDashboardProductsKybIndexRoute,
  authLayoutDashboardProductsRiskAssessmentIndexRoute:
    authLayoutDashboardProductsRiskAssessmentIndexRoute,
}

const authLayoutRouteWithChildren = authLayoutRoute._addFileChildren(
  authLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authLayoutRoute: authLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
